### ISSUE TITLE
Fix ReferenceError: module is not defined

### ISSUE THREAD

**Issue by kalaschnik** [ccp-eva/media-recorder#11]

**Comment by tourze** [comment]
+1

**Comment by kalaschnik** [comment]
Hey @tourze, I entirely rewrote this package (hence the name as well). I’m using now a different bundle output, which also solves the error for: `Fix ReferenceError: module is not defined` 
For the records: This error appeared because there was CJS export syntax in the JavaScript file (`module.exports`) which JavaScript cannot digest.
